### ISSUE TITLE
Support to Update Custom URL plugins only

### ISSUE THREAD

**Issue by maxviewup** [itspriddle/wp-cli-tgmpa-plugin#24]
TGM Allow the use of plugins in custom URL or git repositories, but it doesn't detect new versions of those. Would be nice adding on CLI a way to update those plugins only (just reinstall them, even without updates). Maybe detecting the file size or hash can be an way to check if there is an update, but just forcing it would work fine 😄

**Comment by maxviewup** [comment]
I have tested and it shows Success: Installed 1 of 1 plugins. It Seems that worked.

**Comment by itspriddle** [comment]
@maxviewup v0.2.0 just released, details in #25 and you should be able to do what you need with `wp tgmpa-plugin install --force $(wp tgmpa-plugin list --external --field=name)`

**Comment by maxviewup** [comment]
Great! Will Work great updating private plugins.
