### ISSUE TITLE
Feature request: Cache Plugin Downloads

### ISSUE THREAD

**Issue by AaronRutley** [itspriddle/wp-cli-tgmpa-plugin#29]
It would be awesome if the downloads from WordPress.org were cached (just like wp-cli does by default)!

**Comment by itspriddle** [comment]
Closed by #30 and released as [v0.3.0](https://github.com/itspriddle/wp-cli-tgmpa-plugin/releases/tag/v0.3.0) @AaronRutley @sdenike
